
/**
* array_of_MessageDataHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VS2_klein.idl
* Dienstag, 31. Januar 2017 15:37 Uhr MEZ
*/

public final class array_of_MessageDataHolder implements org.omg.CORBA.portable.Streamable
{
  public MessageData value[] = null;

  public array_of_MessageDataHolder ()
  {
  }

  public array_of_MessageDataHolder (MessageData[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = array_of_MessageDataHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    array_of_MessageDataHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return array_of_MessageDataHelper.type ();
  }

}
