
/**
* ClientMessageboardInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VS2_klein.idl
* Monday, January 30, 2017 9:47:00 AM CET
*/

abstract public class ClientMessageboardInterfaceHelper
{
  private static String  _id = "IDL:ClientMessageboardInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, ClientMessageboardInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ClientMessageboardInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ClientMessageboardInterfaceHelper.id (), "ClientMessageboardInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ClientMessageboardInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ClientMessageboardInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ClientMessageboardInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ClientMessageboardInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ClientMessageboardInterface)
      return (ClientMessageboardInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _ClientMessageboardInterfaceStub stub = new _ClientMessageboardInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ClientMessageboardInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ClientMessageboardInterface)
      return (ClientMessageboardInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _ClientMessageboardInterfaceStub stub = new _ClientMessageboardInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
