
/**
* ClientMessageboardInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VS2_klein.idl
* Dienstag, 31. Januar 2017 15:37 Uhr MEZ
*/

public interface ClientMessageboardInterface extends ClientMessageboardInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ClientMessageboardInterface
