
/**
* ClientMessageboardInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VS2_klein.idl
* Sunday, January 29, 2017 6:31:59 PM CET
*/

public interface ClientMessageboardInterfaceOperations 
{
  MessageData[] getMessages ();
  boolean setMessage (String message, int uid, String uName);
  boolean deleteMessage (int uid);
  boolean createNewMessage (String message, int uid, String uName);
  MessageData getNextMessage ();
  MessageData getPreviousMessage ();
} // interface ClientMessageboardInterfaceOperations
