
/**
* ClientMessageboardInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VS2_klein.idl
* Thursday, January 26, 2017 11:58:00 AM CET
*/

public interface ClientMessageboardInterface extends ClientMessageboardInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ClientMessageboardInterface
