
/**
* ClientMessageboardInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VS2_klein.idl
* Monday, January 30, 2017 9:47:00 AM CET
*/

public interface ClientMessageboardInterfaceOperations 
{
  MessageData[] getMessages ();
  boolean setMessage (String message, int uid, String uName);
  boolean deleteMessage (int uid, MessageData msgData);
  boolean createNewMessage (String message, int uid, String uName);
  MessageData getNextMessage ();
  MessageData getPreviousMessage ();
} // interface ClientMessageboardInterfaceOperations
