
/**
* ClientMessageboardInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VS2_klein.idl
* Monday, January 30, 2017 10:03:34 AM CET
*/

public abstract class ClientMessageboardInterfacePOA extends org.omg.PortableServer.Servant
 implements ClientMessageboardInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getMessages", new java.lang.Integer (0));
    _methods.put ("setMessage", new java.lang.Integer (1));
    _methods.put ("deleteMessage", new java.lang.Integer (2));
    _methods.put ("createNewMessage", new java.lang.Integer (3));
    _methods.put ("getNextMessage", new java.lang.Integer (4));
    _methods.put ("getPreviousMessage", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ClientMessageboardInterface/getMessages
       {
         MessageData $result[] = null;
         $result = this.getMessages ();
         out = $rh.createReply();
         array_of_MessageDataHelper.write (out, $result);
         break;
       }

       case 1:  // ClientMessageboardInterface/setMessage
       {
         String message = in.read_string ();
         int uid = in.read_long ();
         String uName = in.read_string ();
         boolean $result = false;
         $result = this.setMessage (message, uid, uName);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // ClientMessageboardInterface/deleteMessage
       {
         int uid = in.read_long ();
         String messageID = in.read_string ();
         boolean $result = false;
         $result = this.deleteMessage (uid, messageID);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // ClientMessageboardInterface/createNewMessage
       {
         String message = in.read_string ();
         int uid = in.read_long ();
         String uName = in.read_string ();
         boolean $result = false;
         $result = this.createNewMessage (message, uid, uName);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // ClientMessageboardInterface/getNextMessage
       {
         MessageData $result = null;
         $result = this.getNextMessage ();
         out = $rh.createReply();
         MessageDataHelper.write (out, $result);
         break;
       }

       case 5:  // ClientMessageboardInterface/getPreviousMessage
       {
         MessageData $result = null;
         $result = this.getPreviousMessage ();
         out = $rh.createReply();
         MessageDataHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ClientMessageboardInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ClientMessageboardInterface _this() 
  {
    return ClientMessageboardInterfaceHelper.narrow(
    super._this_object());
  }

  public ClientMessageboardInterface _this(org.omg.CORBA.ORB orb) 
  {
    return ClientMessageboardInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class ClientMessageboardInterfacePOA
