
/**
* ClientMessageboardInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VS2_klein.idl
* Sunday, January 29, 2017 6:31:59 PM CET
*/

public interface ClientMessageboardInterface extends ClientMessageboardInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ClientMessageboardInterface
