module Empfang
{
    typedef sequence<string>list;
    interface EmpfangApp
    {
        void send(in string a);
        void benutzername(in string name);
        string getstring();
        list getSTringArray();
    };
};