package VS2idl;


/**
* VS2idl/array_of_MessageDataHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VS2_klein.idl
* Samstag, 28. Januar 2017 02:24 Uhr MEZ
*/

public final class array_of_MessageDataHolder implements org.omg.CORBA.portable.Streamable
{
  public VS2idl.MessageData value[] = null;

  public array_of_MessageDataHolder ()
  {
  }

  public array_of_MessageDataHolder (VS2idl.MessageData[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = VS2idl.array_of_MessageDataHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    VS2idl.array_of_MessageDataHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return VS2idl.array_of_MessageDataHelper.type ();
  }

}
