package VS2idl;

/**
* VS2idl/ClientMessageboardInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VS2_klein.idl
* Samstag, 28. Januar 2017 02:24 Uhr MEZ
*/

public final class ClientMessageboardInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public VS2idl.ClientMessageboardInterface value = null;

  public ClientMessageboardInterfaceHolder ()
  {
  }

  public ClientMessageboardInterfaceHolder (VS2idl.ClientMessageboardInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = VS2idl.ClientMessageboardInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    VS2idl.ClientMessageboardInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return VS2idl.ClientMessageboardInterfaceHelper.type ();
  }

}
