package VS2idl;


/**
* VS2idl/ClientMessageboardInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VS2_klein.idl
* Samstag, 28. Januar 2017 02:24 Uhr MEZ
*/

public interface ClientMessageboardInterfaceOperations 
{
  VS2idl.MessageData[] getMessage ();
  boolean setMessage (String message, int uid, String uName);
  boolean deleteMessage (int uid);
  boolean createNewMessage (String message, int uid, String uName);
  VS2idl.MessageData getNextMessage ();
  VS2idl.MessageData getPreviousMessage ();
} // interface ClientMessageboardInterfaceOperations
