package VS2idl;


/**
* VS2idl/ClientMessageboardInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VS2_klein.idl
* Samstag, 28. Januar 2017 02:24 Uhr MEZ
*/

public interface ClientMessageboardInterface extends ClientMessageboardInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ClientMessageboardInterface
