package VS2idl;

/**
* VS2idl/MessageDataHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VS2_klein.idl
* Samstag, 28. Januar 2017 02:24 Uhr MEZ
*/

public final class MessageDataHolder implements org.omg.CORBA.portable.Streamable
{
  public VS2idl.MessageData value = null;

  public MessageDataHolder ()
  {
  }

  public MessageDataHolder (VS2idl.MessageData initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = VS2idl.MessageDataHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    VS2idl.MessageDataHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return VS2idl.MessageDataHelper.type ();
  }

}
