package VS2;


/**
* VS2/MessageboardServerInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VS2.idl
* Saturday, March 18, 2017 5:22:38 PM CET
*/

public interface MessageboardServerInterfaceOperations 
{
  String getFatherName ();

  //MessageBoard hat fatherId-> abruf xml datei auf fathername
  String[] getChildNames ();
  VS2.MessageData[] getMessages ();
  VS2.MessageData setHighlightedMessage (String messageID);
  VS2.MessageData getHighlightedMessage ();
  VS2.MessageData getMessageWithId (String messageID);
  boolean setMessage (String message, String messageID, int uid, String uName);
  boolean deleteMessage (int uid, String messageID);
  boolean createNewMessage (String message, int uid, String uName);
  VS2.MessageData getNextMessage ();
  VS2.MessageData getPreviousMessage ();
  VS2.ConnectInformationData connectToFather ();

  //Liefert die Connectinformationen des Fathers
  VS2.ConnectInformationData connectToChild (String childName);

  //********** zur Kommunikation zwischen Servern(Spezialfälle, daher notwendig) muss nicht in den Client rein ************************
  boolean publishOnChilds (String message, String messageID, VS2.UserData uData, boolean schalter);

  //Die Nachricht auf allen Kindern veröffentlichen, extra Schalter um auf allen Kindes Kindern zu veröffentlichen?
  boolean publishOnFather (String message, String messageID, VS2.UserData uData);

  //Nachricht auf Vater veröffentlichen
  boolean saveMessage (String message, String messageID, VS2.UserData uData);

  //Wird beim ausführen von publishOnXXX aufgerufen
  void notifyFather ();

  //gebe dem Vater bescheid das du jetzt ein Kind von ihm bist
  void saveFatherInformation (int id, String name, VS2.ConnectInformationData ciData);
  void notifyChildren ();

  //gebe den Kindern bescheid das du jetzt der Vater bist
  void saveChildInformation (int id, String name, VS2.ConnectInformationData ciData);
} // interface MessageboardServerInterfaceOperations
