    typedef sequence<string> array_of_String;//Definition string[], da IDL nicht kennt
	
    struct MessageData
	{
		long uid;
		string id;
		string uName;
		string text;
	};
	
	typedef sequence<MessageData> array_of_MessageData;    

	interface ClientMessageboardInterface
    {
        array_of_MessageData getMessages();
		boolean setMessage(in string message, in long uid, in string uName);
		boolean deleteMessage(in long uid, in MessageData msgData);
		boolean createNewMessage(in string message, in long uid, in string uName);
		MessageData getNextMessage();
		MessageData getPreviousMessage();
	};
