package VS2;

/**
* VS2/ConnectInformationDataHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VS2.idl
* Sonntag, 26. März 2017 17:04 Uhr MESZ
*/

public final class ConnectInformationDataHolder implements org.omg.CORBA.portable.Streamable
{
  public VS2.ConnectInformationData value = null;

  public ConnectInformationDataHolder ()
  {
  }

  public ConnectInformationDataHolder (VS2.ConnectInformationData initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = VS2.ConnectInformationDataHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    VS2.ConnectInformationDataHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return VS2.ConnectInformationDataHelper.type ();
  }

}
