package VS2;


/**
* VS2/MessageboardServerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VS2.idl
* Sonntag, 26. März 2017 17:04 Uhr MESZ
*/

public interface MessageboardServerInterface extends MessageboardServerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface MessageboardServerInterface
