package Empfang;


/**
* Empfang/EmpfangAppOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Empfang.idl
* Dienstag, 6. Dezember 2016 15:41 Uhr MEZ
*/

public interface EmpfangAppOperations 
{
  void send (String a);
  void benutzername (String name);
  String getstring ();
  String[] getSTringArray ();
} // interface EmpfangAppOperations
