package Empfang;


/**
* Empfang/EmpfangAppHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Empfang.idl
* Dienstag, 6. Dezember 2016 15:41 Uhr MEZ
*/

abstract public class EmpfangAppHelper
{
  private static String  _id = "IDL:Empfang/EmpfangApp:1.0";

  public static void insert (org.omg.CORBA.Any a, Empfang.EmpfangApp that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Empfang.EmpfangApp extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Empfang.EmpfangAppHelper.id (), "EmpfangApp");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Empfang.EmpfangApp read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_EmpfangAppStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Empfang.EmpfangApp value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Empfang.EmpfangApp narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Empfang.EmpfangApp)
      return (Empfang.EmpfangApp)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Empfang._EmpfangAppStub stub = new Empfang._EmpfangAppStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Empfang.EmpfangApp unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Empfang.EmpfangApp)
      return (Empfang.EmpfangApp)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Empfang._EmpfangAppStub stub = new Empfang._EmpfangAppStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
