package Empfang;


/**
* Empfang/listHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Empfang.idl
* Dienstag, 6. Dezember 2016 15:41 Uhr MEZ
*/

public final class listHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public listHolder ()
  {
  }

  public listHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Empfang.listHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Empfang.listHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Empfang.listHelper.type ();
  }

}
