package VS2;


/**
* VS2/LoginServerInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VS2.idl
* Montag, 27. März 2017 11:16 Uhr MESZ
*/

public interface LoginServerInterfaceOperations 
{
  VS2.LoginInformation login (VS2.UserData uData);
  boolean reg (VS2.UserData uData, String regData);
} // interface LoginServerInterfaceOperations
