package VS2;


/**
* VS2/LoginServerInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VS2.idl
* Tuesday, January 31, 2017 6:35:56 PM CET
*/

public interface LoginServerInterfaceOperations 
{
  VS2.LoginInformation login (VS2.UserData uData);
  boolean reg (VS2.UserData uData, String regData);
} // interface LoginServerInterfaceOperations
