package VS2;


/**
* VS2/MessageboardServerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VS2.idl
* Tuesday, March 21, 2017 11:10:23 AM CET
*/

public interface MessageboardServerInterface extends MessageboardServerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface MessageboardServerInterface
