package VS2;


/**
* VS2/MessageboardServerInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VS2.idl
* Sonntag, 26. M�rz 2017 14:55 Uhr MESZ
*/

public interface MessageboardServerInterfaceOperations 
{
  String getFatherName ();

  //MessageBoard hat fatherId-> abruf xml datei auf fathername
  String[] getChildNames ();
  VS2.MessageData[] getMessages ();
  VS2.MessageData setHighlightedMessage (String messageID);
  VS2.MessageData getHighlightedMessage ();
  VS2.MessageData getMessageWithId (String messageID);
  boolean setMessage (String message, String messageID, VS2.UserData uData);
  boolean deleteMessage (String messageID, VS2.UserData uData);
  boolean createNewMessage (String message, VS2.UserData uData);
  VS2.MessageData getNextMessage ();
  VS2.MessageData getPreviousMessage ();
  VS2.ConnectInformationData connectToFather (VS2.UserData uData);

  //Liefert die Connectinformationen des Fathers
  VS2.ConnectInformationData connectToChild (String childName);

  //********** zur Kommunikation zwischen Servern(Spezialfälle, daher notwendig) muss nicht in den Client rein ************************
  boolean publishOnChilds (String message, String messageID, VS2.UserData uData, boolean schalter);

  //Die Nachricht auf allen Kindern veröffentlichen, extra Schalter um auf allen Kindes Kindern zu veröffentlichen?
  boolean publishOnFather (String message, String messageID, VS2.UserData uData);

  //Nachricht auf Vater veröffentlichen
  boolean saveMessage (String message, String messageID, VS2.UserData uData);

  //Wird beim ausführen von publishOnXXX aufgerufen
  void notifyFather (VS2.UserData uData);

  //gebe dem Vater bescheid das du jetzt ein Kind von ihm bist
  void saveFatherInformation (int id, String name, VS2.ConnectInformationData ciData, VS2.UserData uData);
  void notifyChildren (VS2.UserData uData);

  //gebe den Kindern bescheid das du jetzt der Vater bist
  void saveChildInformation (int id, String name, VS2.ConnectInformationData ciData, VS2.UserData uData);

  //Method Calls für SOAP-Server
  boolean createMessageSoap (String message, String messageID, int serverNr, VS2.UserData uData);
  boolean modifyMessageSoap (String message, String messageID, int serverNr, VS2.UserData uData);
  boolean deleteMessageSoap (String messageID, VS2.UserData uData);
} // interface MessageboardServerInterfaceOperations
