package VS2;


/**
* VS2/MessageboardServerInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VS2.idl
* Tuesday, January 31, 2017 6:35:56 PM CET
*/

public interface MessageboardServerInterfaceOperations 
{
  String getFatherName ();

  //MessageBoard hat fatherId-> abruf xml datei auf fathername
  String[] getChildNames ();
  VS2.MessageData[] getMessages ();
  VS2.MessageData setHighlightedMessage (String messageID);
  VS2.MessageData getHighlightedMessage ();
  VS2.MessageData getMessageWithId (String messageID);
  boolean setMessage (String message, String messageID, int uid, String uName);
  boolean deleteMessage (int uid, String messageID);
  boolean createNewMessage (String message, int uid, String uName);
  VS2.MessageData getNextMessage ();
  VS2.MessageData getPreviousMessage ();
  VS2.ConnectInformationData connectToFather ();

  //Liefert die Connectinformationen des Fathers
  VS2.ConnectInformationData connectToChild (String childName);

  //Liefert die ConnectInformationen des Childs
  boolean iterateChilds (String message, String messageID, int uid, String uName, boolean schalter);

  //Die Nachricht auf allen Kindern veröffentlichen, extra Schalter um auf allen Kindes Kindern zu veröffentlichen?
  boolean publishOnFather (String message, String messageID, int uid, String uName);

  //********** zur Kommunikation zwischen Servern(Spezialfälle, daher notwendig) muss nicht in den Client rein ************************
  boolean publishChild (String message, int uid, String uName, boolean schalter);

  //veröffentliche Nachricht auf Kinderboards
  boolean publishFather (String message, int uid, String uName);

  //Veröffentlich Nachricht auf Vaterboard
  void notifyFather ();

  //gebe dem Vater bescheid das du jetzt ein Kind von ihm bist
  void saveFatherInformation (int id, String name, VS2.ConnectInformationData ciData);
  void notifyChildren ();

  //gebe den Kindern bescheid das du jetzt der Vater bist
  void saveChildInformation (int id, String name, VS2.ConnectInformationData ciData);
} // interface MessageboardServerInterfaceOperations
