package VS2;


/**
* VS2/UserData.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VS2.idl
* Tuesday, January 31, 2017 6:35:56 PM CET
*/

public final class UserData implements org.omg.CORBA.portable.IDLEntity
{
  public String userName = null;
  public String password = null;

  public UserData ()
  {
  } // ctor

  public UserData (String _userName, String _password)
  {
    userName = _userName;
    password = _password;
  } // ctor

} // class UserData
