package VS2;


/**
* VS2/UserData.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VS2.idl
* Sonntag, 26. März 2017 18:12 Uhr MESZ
*/

public final class UserData implements org.omg.CORBA.portable.IDLEntity
{
  public int userID = (int)0;
  public String userName = null;
  public String password = null;
  public boolean isAdmin = false;

  public UserData ()
  {
  } // ctor

  public UserData (int _userID, String _userName, String _password, boolean _isAdmin)
  {
    userID = _userID;
    userName = _userName;
    password = _password;
    isAdmin = _isAdmin;
  } // ctor

} // class UserData
