// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.

#include "VS2_klein.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_2;



void
ConnectInformationData::operator>>= (cdrStream &_n) const
{
  _n.marshalString(ip,0);
  port >>= _n;

}

void
ConnectInformationData::operator<<= (cdrStream &_n)
{
  ip = _n.unmarshalString(0);
  (::CORBA::Long&)port <<= _n;

}

void
MessageData::operator>>= (cdrStream &_n) const
{
  uid >>= _n;
  _n.marshalString(id,0);
  _n.marshalString(uName,0);
  _n.marshalString(text,0);

}

void
MessageData::operator<<= (cdrStream &_n)
{
  (::CORBA::Long&)uid <<= _n;
  id = _n.unmarshalString(0);
  uName = _n.unmarshalString(0);
  text = _n.unmarshalString(0);

}

ClientMessageboardInterface_ptr ClientMessageboardInterface_Helper::_nil() {
  return ::ClientMessageboardInterface::_nil();
}

::CORBA::Boolean ClientMessageboardInterface_Helper::is_nil(::ClientMessageboardInterface_ptr p) {
  return ::CORBA::is_nil(p);

}

void ClientMessageboardInterface_Helper::release(::ClientMessageboardInterface_ptr p) {
  ::CORBA::release(p);
}

void ClientMessageboardInterface_Helper::marshalObjRef(::ClientMessageboardInterface_ptr obj, cdrStream& s) {
  ::ClientMessageboardInterface::_marshalObjRef(obj, s);
}

ClientMessageboardInterface_ptr ClientMessageboardInterface_Helper::unmarshalObjRef(cdrStream& s) {
  return ::ClientMessageboardInterface::_unmarshalObjRef(s);
}

void ClientMessageboardInterface_Helper::duplicate(::ClientMessageboardInterface_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

ClientMessageboardInterface_ptr
ClientMessageboardInterface::_duplicate(::ClientMessageboardInterface_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

ClientMessageboardInterface_ptr
ClientMessageboardInterface::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


ClientMessageboardInterface_ptr
ClientMessageboardInterface::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

ClientMessageboardInterface_ptr
ClientMessageboardInterface::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_ClientMessageboardInterface _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_ClientMessageboardInterface* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_ClientMessageboardInterface;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* ClientMessageboardInterface::_PD_repoId = "IDL:ClientMessageboardInterface:1.0";


_objref_ClientMessageboardInterface::~_objref_ClientMessageboardInterface() {
  
}


_objref_ClientMessageboardInterface::_objref_ClientMessageboardInterface(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::ClientMessageboardInterface::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
_objref_ClientMessageboardInterface::_ptrToObjRef(const char* id)
{
  if (id == ::ClientMessageboardInterface::_PD_repoId)
    return (::ClientMessageboardInterface_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::ClientMessageboardInterface::_PD_repoId))
    return (::ClientMessageboardInterface_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for ClientMessageboardInterface::getFatherName

// Proxy call descriptor class. Mangled signature:
//  _cstring
class _0RL_cd_1157ac065cc2e43d_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_1157ac065cc2e43d_00000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::String_var result;
};

void _0RL_cd_1157ac065cc2e43d_00000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalString(result,0);

}

void _0RL_cd_1157ac065cc2e43d_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalString(0);

}

const char* const _0RL_cd_1157ac065cc2e43d_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_1157ac065cc2e43d_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_1157ac065cc2e43d_00000000* tcd = (_0RL_cd_1157ac065cc2e43d_00000000*)cd;
  _impl_ClientMessageboardInterface* impl = (_impl_ClientMessageboardInterface*) svnt->_ptrToInterface(ClientMessageboardInterface::_PD_repoId);
  tcd->result = impl->getFatherName();


}

char* _objref_ClientMessageboardInterface::getFatherName()
{
  _0RL_cd_1157ac065cc2e43d_00000000 _call_desc(_0RL_lcfn_1157ac065cc2e43d_10000000, "getFatherName", 14);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for ClientMessageboardInterface::getChildNames

// Proxy call descriptor class. Mangled signature:
//  _carray__of__String
class _0RL_cd_1157ac065cc2e43d_20000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_1157ac065cc2e43d_20000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  array_of_String_var result;
};

void _0RL_cd_1157ac065cc2e43d_20000000::marshalReturnedValues(cdrStream& _n)
{
  (const array_of_String&) result >>= _n;

}

void _0RL_cd_1157ac065cc2e43d_20000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new array_of_String;
  (array_of_String&)result <<= _n;

}

const char* const _0RL_cd_1157ac065cc2e43d_20000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_1157ac065cc2e43d_30000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_1157ac065cc2e43d_20000000* tcd = (_0RL_cd_1157ac065cc2e43d_20000000*)cd;
  _impl_ClientMessageboardInterface* impl = (_impl_ClientMessageboardInterface*) svnt->_ptrToInterface(ClientMessageboardInterface::_PD_repoId);
  tcd->result = impl->getChildNames();


}

array_of_String* _objref_ClientMessageboardInterface::getChildNames()
{
  _0RL_cd_1157ac065cc2e43d_20000000 _call_desc(_0RL_lcfn_1157ac065cc2e43d_30000000, "getChildNames", 14);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for ClientMessageboardInterface::getMessages

// Proxy call descriptor class. Mangled signature:
//  _carray__of__MessageData
class _0RL_cd_1157ac065cc2e43d_40000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_1157ac065cc2e43d_40000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  array_of_MessageData_var result;
};

void _0RL_cd_1157ac065cc2e43d_40000000::marshalReturnedValues(cdrStream& _n)
{
  (const array_of_MessageData&) result >>= _n;

}

void _0RL_cd_1157ac065cc2e43d_40000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new array_of_MessageData;
  (array_of_MessageData&)result <<= _n;

}

const char* const _0RL_cd_1157ac065cc2e43d_40000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_1157ac065cc2e43d_50000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_1157ac065cc2e43d_40000000* tcd = (_0RL_cd_1157ac065cc2e43d_40000000*)cd;
  _impl_ClientMessageboardInterface* impl = (_impl_ClientMessageboardInterface*) svnt->_ptrToInterface(ClientMessageboardInterface::_PD_repoId);
  tcd->result = impl->getMessages();


}

array_of_MessageData* _objref_ClientMessageboardInterface::getMessages()
{
  _0RL_cd_1157ac065cc2e43d_40000000 _call_desc(_0RL_lcfn_1157ac065cc2e43d_50000000, "getMessages", 12);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for ClientMessageboardInterface::setHighlightedMessage

// Proxy call descriptor class. Mangled signature:
//  _cMessageData_i_cstring
class _0RL_cd_1157ac065cc2e43d_60000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_1157ac065cc2e43d_60000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
  MessageData_var result;
};

void _0RL_cd_1157ac065cc2e43d_60000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);

}

void _0RL_cd_1157ac065cc2e43d_60000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();

}

void _0RL_cd_1157ac065cc2e43d_60000000::marshalReturnedValues(cdrStream& _n)
{
  (const MessageData&) result >>= _n;

}

void _0RL_cd_1157ac065cc2e43d_60000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new MessageData;
  (MessageData&)result <<= _n;

}

const char* const _0RL_cd_1157ac065cc2e43d_60000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_1157ac065cc2e43d_70000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_1157ac065cc2e43d_60000000* tcd = (_0RL_cd_1157ac065cc2e43d_60000000*)cd;
  _impl_ClientMessageboardInterface* impl = (_impl_ClientMessageboardInterface*) svnt->_ptrToInterface(ClientMessageboardInterface::_PD_repoId);
  tcd->result = impl->setHighlightedMessage(tcd->arg_0);


}

MessageData* _objref_ClientMessageboardInterface::setHighlightedMessage(const char* messageID)
{
  _0RL_cd_1157ac065cc2e43d_60000000 _call_desc(_0RL_lcfn_1157ac065cc2e43d_70000000, "setHighlightedMessage", 22);
  _call_desc.arg_0 = messageID;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for ClientMessageboardInterface::getHighlightedMessage

// Proxy call descriptor class. Mangled signature:
//  _cMessageData
class _0RL_cd_1157ac065cc2e43d_80000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_1157ac065cc2e43d_80000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  MessageData_var result;
};

void _0RL_cd_1157ac065cc2e43d_80000000::marshalReturnedValues(cdrStream& _n)
{
  (const MessageData&) result >>= _n;

}

void _0RL_cd_1157ac065cc2e43d_80000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new MessageData;
  (MessageData&)result <<= _n;

}

const char* const _0RL_cd_1157ac065cc2e43d_80000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_1157ac065cc2e43d_90000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_1157ac065cc2e43d_80000000* tcd = (_0RL_cd_1157ac065cc2e43d_80000000*)cd;
  _impl_ClientMessageboardInterface* impl = (_impl_ClientMessageboardInterface*) svnt->_ptrToInterface(ClientMessageboardInterface::_PD_repoId);
  tcd->result = impl->getHighlightedMessage();


}

MessageData* _objref_ClientMessageboardInterface::getHighlightedMessage()
{
  _0RL_cd_1157ac065cc2e43d_80000000 _call_desc(_0RL_lcfn_1157ac065cc2e43d_90000000, "getHighlightedMessage", 22);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for ClientMessageboardInterface::getMessageWithId

// Local call call-back function.
static void
_0RL_lcfn_1157ac065cc2e43d_a0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_1157ac065cc2e43d_60000000* tcd = (_0RL_cd_1157ac065cc2e43d_60000000*)cd;
  _impl_ClientMessageboardInterface* impl = (_impl_ClientMessageboardInterface*) svnt->_ptrToInterface(ClientMessageboardInterface::_PD_repoId);
  tcd->result = impl->getMessageWithId(tcd->arg_0);


}

MessageData* _objref_ClientMessageboardInterface::getMessageWithId(const char* messageID)
{
  _0RL_cd_1157ac065cc2e43d_60000000 _call_desc(_0RL_lcfn_1157ac065cc2e43d_a0000000, "getMessageWithId", 17);
  _call_desc.arg_0 = messageID;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for ClientMessageboardInterface::setMessage

// Proxy call descriptor class. Mangled signature:
//  _cboolean_i_cstring_i_cstring_i_clong_i_cstring
class _0RL_cd_1157ac065cc2e43d_b0000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_1157ac065cc2e43d_b0000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
  ::CORBA::String_var arg_1_;
  const char* arg_1;
  ::CORBA::Long arg_2;
  ::CORBA::String_var arg_3_;
  const char* arg_3;
  ::CORBA::Boolean result;
};

void _0RL_cd_1157ac065cc2e43d_b0000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);
  _n.marshalString(arg_1,0);
  arg_2 >>= _n;
  _n.marshalString(arg_3,0);

}

void _0RL_cd_1157ac065cc2e43d_b0000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();
  arg_1_ = _n.unmarshalString(0);
  arg_1 = arg_1_.in();
  (::CORBA::Long&)arg_2 <<= _n;
  arg_3_ = _n.unmarshalString(0);
  arg_3 = arg_3_.in();

}

void _0RL_cd_1157ac065cc2e43d_b0000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);

}

void _0RL_cd_1157ac065cc2e43d_b0000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();

}

const char* const _0RL_cd_1157ac065cc2e43d_b0000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_1157ac065cc2e43d_c0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_1157ac065cc2e43d_b0000000* tcd = (_0RL_cd_1157ac065cc2e43d_b0000000*)cd;
  _impl_ClientMessageboardInterface* impl = (_impl_ClientMessageboardInterface*) svnt->_ptrToInterface(ClientMessageboardInterface::_PD_repoId);
  tcd->result = impl->setMessage(tcd->arg_0, tcd->arg_1, tcd->arg_2, tcd->arg_3);


}

::CORBA::Boolean _objref_ClientMessageboardInterface::setMessage(const char* message, const char* messageID, ::CORBA::Long uid, const char* uName)
{
  _0RL_cd_1157ac065cc2e43d_b0000000 _call_desc(_0RL_lcfn_1157ac065cc2e43d_c0000000, "setMessage", 11);
  _call_desc.arg_0 = message;
  _call_desc.arg_1 = messageID;
  _call_desc.arg_2 = uid;
  _call_desc.arg_3 = uName;

  _invoke(_call_desc);
  return _call_desc.result;


}


//
// Code for ClientMessageboardInterface::deleteMessage

// Proxy call descriptor class. Mangled signature:
//  _cboolean_i_clong_i_cstring
class _0RL_cd_1157ac065cc2e43d_d0000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_1157ac065cc2e43d_d0000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Long arg_0;
  ::CORBA::String_var arg_1_;
  const char* arg_1;
  ::CORBA::Boolean result;
};

void _0RL_cd_1157ac065cc2e43d_d0000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  _n.marshalString(arg_1,0);

}

void _0RL_cd_1157ac065cc2e43d_d0000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Long&)arg_0 <<= _n;
  arg_1_ = _n.unmarshalString(0);
  arg_1 = arg_1_.in();

}

void _0RL_cd_1157ac065cc2e43d_d0000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);

}

void _0RL_cd_1157ac065cc2e43d_d0000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();

}

const char* const _0RL_cd_1157ac065cc2e43d_d0000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_1157ac065cc2e43d_e0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_1157ac065cc2e43d_d0000000* tcd = (_0RL_cd_1157ac065cc2e43d_d0000000*)cd;
  _impl_ClientMessageboardInterface* impl = (_impl_ClientMessageboardInterface*) svnt->_ptrToInterface(ClientMessageboardInterface::_PD_repoId);
  tcd->result = impl->deleteMessage(tcd->arg_0, tcd->arg_1);


}

::CORBA::Boolean _objref_ClientMessageboardInterface::deleteMessage(::CORBA::Long uid, const char* messageID)
{
  _0RL_cd_1157ac065cc2e43d_d0000000 _call_desc(_0RL_lcfn_1157ac065cc2e43d_e0000000, "deleteMessage", 14);
  _call_desc.arg_0 = uid;
  _call_desc.arg_1 = messageID;

  _invoke(_call_desc);
  return _call_desc.result;


}


//
// Code for ClientMessageboardInterface::createNewMessage

// Proxy call descriptor class. Mangled signature:
//  _cboolean_i_cstring_i_clong_i_cstring
class _0RL_cd_1157ac065cc2e43d_f0000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_1157ac065cc2e43d_f0000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
  ::CORBA::Long arg_1;
  ::CORBA::String_var arg_2_;
  const char* arg_2;
  ::CORBA::Boolean result;
};

void _0RL_cd_1157ac065cc2e43d_f0000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);
  arg_1 >>= _n;
  _n.marshalString(arg_2,0);

}

void _0RL_cd_1157ac065cc2e43d_f0000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();
  (::CORBA::Long&)arg_1 <<= _n;
  arg_2_ = _n.unmarshalString(0);
  arg_2 = arg_2_.in();

}

void _0RL_cd_1157ac065cc2e43d_f0000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);

}

void _0RL_cd_1157ac065cc2e43d_f0000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();

}

const char* const _0RL_cd_1157ac065cc2e43d_f0000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_1157ac065cc2e43d_01000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_1157ac065cc2e43d_f0000000* tcd = (_0RL_cd_1157ac065cc2e43d_f0000000*)cd;
  _impl_ClientMessageboardInterface* impl = (_impl_ClientMessageboardInterface*) svnt->_ptrToInterface(ClientMessageboardInterface::_PD_repoId);
  tcd->result = impl->createNewMessage(tcd->arg_0, tcd->arg_1, tcd->arg_2);


}

::CORBA::Boolean _objref_ClientMessageboardInterface::createNewMessage(const char* message, ::CORBA::Long uid, const char* uName)
{
  _0RL_cd_1157ac065cc2e43d_f0000000 _call_desc(_0RL_lcfn_1157ac065cc2e43d_01000000, "createNewMessage", 17);
  _call_desc.arg_0 = message;
  _call_desc.arg_1 = uid;
  _call_desc.arg_2 = uName;

  _invoke(_call_desc);
  return _call_desc.result;


}


//
// Code for ClientMessageboardInterface::getNextMessage

// Local call call-back function.
static void
_0RL_lcfn_1157ac065cc2e43d_11000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_1157ac065cc2e43d_80000000* tcd = (_0RL_cd_1157ac065cc2e43d_80000000*)cd;
  _impl_ClientMessageboardInterface* impl = (_impl_ClientMessageboardInterface*) svnt->_ptrToInterface(ClientMessageboardInterface::_PD_repoId);
  tcd->result = impl->getNextMessage();


}

MessageData* _objref_ClientMessageboardInterface::getNextMessage()
{
  _0RL_cd_1157ac065cc2e43d_80000000 _call_desc(_0RL_lcfn_1157ac065cc2e43d_11000000, "getNextMessage", 15);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for ClientMessageboardInterface::getPreviousMessage

// Local call call-back function.
static void
_0RL_lcfn_1157ac065cc2e43d_21000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_1157ac065cc2e43d_80000000* tcd = (_0RL_cd_1157ac065cc2e43d_80000000*)cd;
  _impl_ClientMessageboardInterface* impl = (_impl_ClientMessageboardInterface*) svnt->_ptrToInterface(ClientMessageboardInterface::_PD_repoId);
  tcd->result = impl->getPreviousMessage();


}

MessageData* _objref_ClientMessageboardInterface::getPreviousMessage()
{
  _0RL_cd_1157ac065cc2e43d_80000000 _call_desc(_0RL_lcfn_1157ac065cc2e43d_21000000, "getPreviousMessage", 19);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for ClientMessageboardInterface::connectToFather

// Proxy call descriptor class. Mangled signature:
//  _cConnectInformationData
class _0RL_cd_1157ac065cc2e43d_31000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_1157ac065cc2e43d_31000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ConnectInformationData_var result;
};

void _0RL_cd_1157ac065cc2e43d_31000000::marshalReturnedValues(cdrStream& _n)
{
  (const ConnectInformationData&) result >>= _n;

}

void _0RL_cd_1157ac065cc2e43d_31000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new ConnectInformationData;
  (ConnectInformationData&)result <<= _n;

}

const char* const _0RL_cd_1157ac065cc2e43d_31000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_1157ac065cc2e43d_41000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_1157ac065cc2e43d_31000000* tcd = (_0RL_cd_1157ac065cc2e43d_31000000*)cd;
  _impl_ClientMessageboardInterface* impl = (_impl_ClientMessageboardInterface*) svnt->_ptrToInterface(ClientMessageboardInterface::_PD_repoId);
  tcd->result = impl->connectToFather();


}

ConnectInformationData* _objref_ClientMessageboardInterface::connectToFather()
{
  _0RL_cd_1157ac065cc2e43d_31000000 _call_desc(_0RL_lcfn_1157ac065cc2e43d_41000000, "connectToFather", 16);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for ClientMessageboardInterface::connectToChild

// Proxy call descriptor class. Mangled signature:
//  _cConnectInformationData_i_cstring
class _0RL_cd_1157ac065cc2e43d_51000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_1157ac065cc2e43d_51000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
  ConnectInformationData_var result;
};

void _0RL_cd_1157ac065cc2e43d_51000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);

}

void _0RL_cd_1157ac065cc2e43d_51000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();

}

void _0RL_cd_1157ac065cc2e43d_51000000::marshalReturnedValues(cdrStream& _n)
{
  (const ConnectInformationData&) result >>= _n;

}

void _0RL_cd_1157ac065cc2e43d_51000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new ConnectInformationData;
  (ConnectInformationData&)result <<= _n;

}

const char* const _0RL_cd_1157ac065cc2e43d_51000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_1157ac065cc2e43d_61000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_1157ac065cc2e43d_51000000* tcd = (_0RL_cd_1157ac065cc2e43d_51000000*)cd;
  _impl_ClientMessageboardInterface* impl = (_impl_ClientMessageboardInterface*) svnt->_ptrToInterface(ClientMessageboardInterface::_PD_repoId);
  tcd->result = impl->connectToChild(tcd->arg_0);


}

ConnectInformationData* _objref_ClientMessageboardInterface::connectToChild(const char* childName)
{
  _0RL_cd_1157ac065cc2e43d_51000000 _call_desc(_0RL_lcfn_1157ac065cc2e43d_61000000, "connectToChild", 15);
  _call_desc.arg_0 = childName;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}

_pof_ClientMessageboardInterface::~_pof_ClientMessageboardInterface() {}


omniObjRef*
_pof_ClientMessageboardInterface::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::_objref_ClientMessageboardInterface(ior, id);
}


::CORBA::Boolean
_pof_ClientMessageboardInterface::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::ClientMessageboardInterface::_PD_repoId))
    return 1;
  
  return 0;
}

const _pof_ClientMessageboardInterface _the_pof_ClientMessageboardInterface;

_impl_ClientMessageboardInterface::~_impl_ClientMessageboardInterface() {}


::CORBA::Boolean
_impl_ClientMessageboardInterface::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "getFatherName")) {

    _0RL_cd_1157ac065cc2e43d_00000000 _call_desc(_0RL_lcfn_1157ac065cc2e43d_10000000, "getFatherName", 14, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "getChildNames")) {

    _0RL_cd_1157ac065cc2e43d_20000000 _call_desc(_0RL_lcfn_1157ac065cc2e43d_30000000, "getChildNames", 14, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "getMessages")) {

    _0RL_cd_1157ac065cc2e43d_40000000 _call_desc(_0RL_lcfn_1157ac065cc2e43d_50000000, "getMessages", 12, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "setHighlightedMessage")) {

    _0RL_cd_1157ac065cc2e43d_60000000 _call_desc(_0RL_lcfn_1157ac065cc2e43d_70000000, "setHighlightedMessage", 22, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "getHighlightedMessage")) {

    _0RL_cd_1157ac065cc2e43d_80000000 _call_desc(_0RL_lcfn_1157ac065cc2e43d_90000000, "getHighlightedMessage", 22, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "getMessageWithId")) {

    _0RL_cd_1157ac065cc2e43d_60000000 _call_desc(_0RL_lcfn_1157ac065cc2e43d_a0000000, "getMessageWithId", 17, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "setMessage")) {

    _0RL_cd_1157ac065cc2e43d_b0000000 _call_desc(_0RL_lcfn_1157ac065cc2e43d_c0000000, "setMessage", 11, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "deleteMessage")) {

    _0RL_cd_1157ac065cc2e43d_d0000000 _call_desc(_0RL_lcfn_1157ac065cc2e43d_e0000000, "deleteMessage", 14, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "createNewMessage")) {

    _0RL_cd_1157ac065cc2e43d_f0000000 _call_desc(_0RL_lcfn_1157ac065cc2e43d_01000000, "createNewMessage", 17, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "getNextMessage")) {

    _0RL_cd_1157ac065cc2e43d_80000000 _call_desc(_0RL_lcfn_1157ac065cc2e43d_11000000, "getNextMessage", 15, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "getPreviousMessage")) {

    _0RL_cd_1157ac065cc2e43d_80000000 _call_desc(_0RL_lcfn_1157ac065cc2e43d_21000000, "getPreviousMessage", 19, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "connectToFather")) {

    _0RL_cd_1157ac065cc2e43d_31000000 _call_desc(_0RL_lcfn_1157ac065cc2e43d_41000000, "connectToFather", 16, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "connectToChild")) {

    _0RL_cd_1157ac065cc2e43d_51000000 _call_desc(_0RL_lcfn_1157ac065cc2e43d_61000000, "connectToChild", 15, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
_impl_ClientMessageboardInterface::_ptrToInterface(const char* id)
{
  if (id == ::ClientMessageboardInterface::_PD_repoId)
    return (::_impl_ClientMessageboardInterface*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::ClientMessageboardInterface::_PD_repoId))
    return (::_impl_ClientMessageboardInterface*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
_impl_ClientMessageboardInterface::_mostDerivedRepoId()
{
  return ::ClientMessageboardInterface::_PD_repoId;
}

POA_ClientMessageboardInterface::~POA_ClientMessageboardInterface() {}

