// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.

#include "VS2.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_2;



void
VS2::ConnectInformationData::operator>>= (cdrStream &_n) const
{
  _n.marshalString(ip,0);
  port >>= _n;

}

void
VS2::ConnectInformationData::operator<<= (cdrStream &_n)
{
  ip = _n.unmarshalString(0);
  (::CORBA::Long&)port <<= _n;

}

void
VS2::UserData::operator>>= (cdrStream &_n) const
{
  userID >>= _n;
  _n.marshalString(userName,0);
  _n.marshalString(password,0);
  _n.marshalBoolean(isAdmin);

}

void
VS2::UserData::operator<<= (cdrStream &_n)
{
  (::CORBA::Long&)userID <<= _n;
  userName = _n.unmarshalString(0);
  password = _n.unmarshalString(0);
  isAdmin = _n.unmarshalBoolean();

}

void
VS2::LoginInformation::operator>>= (cdrStream &_n) const
{
  _n.marshalBoolean(adminRights);
  (const ConnectInformationData&) server >>= _n;

}

void
VS2::LoginInformation::operator<<= (cdrStream &_n)
{
  adminRights = _n.unmarshalBoolean();
  (ConnectInformationData&)server <<= _n;

}

void
VS2::MessageData::operator>>= (cdrStream &_n) const
{
  uid >>= _n;
  _n.marshalString(id,0);
  _n.marshalString(uName,0);
  _n.marshalString(text,0);

}

void
VS2::MessageData::operator<<= (cdrStream &_n)
{
  (::CORBA::Long&)uid <<= _n;
  id = _n.unmarshalString(0);
  uName = _n.unmarshalString(0);
  text = _n.unmarshalString(0);

}

VS2::MessageboardServerInterface_ptr VS2::MessageboardServerInterface_Helper::_nil() {
  return ::VS2::MessageboardServerInterface::_nil();
}

::CORBA::Boolean VS2::MessageboardServerInterface_Helper::is_nil(::VS2::MessageboardServerInterface_ptr p) {
  return ::CORBA::is_nil(p);

}

void VS2::MessageboardServerInterface_Helper::release(::VS2::MessageboardServerInterface_ptr p) {
  ::CORBA::release(p);
}

void VS2::MessageboardServerInterface_Helper::marshalObjRef(::VS2::MessageboardServerInterface_ptr obj, cdrStream& s) {
  ::VS2::MessageboardServerInterface::_marshalObjRef(obj, s);
}

VS2::MessageboardServerInterface_ptr VS2::MessageboardServerInterface_Helper::unmarshalObjRef(cdrStream& s) {
  return ::VS2::MessageboardServerInterface::_unmarshalObjRef(s);
}

void VS2::MessageboardServerInterface_Helper::duplicate(::VS2::MessageboardServerInterface_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

VS2::MessageboardServerInterface_ptr
VS2::MessageboardServerInterface::_duplicate(::VS2::MessageboardServerInterface_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

VS2::MessageboardServerInterface_ptr
VS2::MessageboardServerInterface::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


VS2::MessageboardServerInterface_ptr
VS2::MessageboardServerInterface::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

VS2::MessageboardServerInterface_ptr
VS2::MessageboardServerInterface::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_MessageboardServerInterface _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_MessageboardServerInterface* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_MessageboardServerInterface;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* VS2::MessageboardServerInterface::_PD_repoId = "IDL:VS2/MessageboardServerInterface:1.0";


VS2::_objref_MessageboardServerInterface::~_objref_MessageboardServerInterface() {
  
}


VS2::_objref_MessageboardServerInterface::_objref_MessageboardServerInterface(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::VS2::MessageboardServerInterface::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
VS2::_objref_MessageboardServerInterface::_ptrToObjRef(const char* id)
{
  if (id == ::VS2::MessageboardServerInterface::_PD_repoId)
    return (::VS2::MessageboardServerInterface_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::VS2::MessageboardServerInterface::_PD_repoId))
    return (::VS2::MessageboardServerInterface_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for VS2::MessageboardServerInterface::getFatherName

// Proxy call descriptor class. Mangled signature:
//  _cstring
class _0RL_cd_446db2b6595c77cf_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_446db2b6595c77cf_00000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::String_var result;
};

void _0RL_cd_446db2b6595c77cf_00000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalString(result,0);

}

void _0RL_cd_446db2b6595c77cf_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalString(0);

}

const char* const _0RL_cd_446db2b6595c77cf_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_446db2b6595c77cf_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_446db2b6595c77cf_00000000* tcd = (_0RL_cd_446db2b6595c77cf_00000000*)cd;
  VS2::_impl_MessageboardServerInterface* impl = (VS2::_impl_MessageboardServerInterface*) svnt->_ptrToInterface(VS2::MessageboardServerInterface::_PD_repoId);
  tcd->result = impl->getFatherName();


}

char* VS2::_objref_MessageboardServerInterface::getFatherName()
{
  _0RL_cd_446db2b6595c77cf_00000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_10000000, "getFatherName", 14);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for VS2::MessageboardServerInterface::getChildNames

// Proxy call descriptor class. Mangled signature:
//  _cVS2_marray__of__String
class _0RL_cd_446db2b6595c77cf_20000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_446db2b6595c77cf_20000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  VS2::array_of_String_var result;
};

void _0RL_cd_446db2b6595c77cf_20000000::marshalReturnedValues(cdrStream& _n)
{
  (const VS2::array_of_String&) result >>= _n;

}

void _0RL_cd_446db2b6595c77cf_20000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new VS2::array_of_String;
  (VS2::array_of_String&)result <<= _n;

}

const char* const _0RL_cd_446db2b6595c77cf_20000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_446db2b6595c77cf_30000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_446db2b6595c77cf_20000000* tcd = (_0RL_cd_446db2b6595c77cf_20000000*)cd;
  VS2::_impl_MessageboardServerInterface* impl = (VS2::_impl_MessageboardServerInterface*) svnt->_ptrToInterface(VS2::MessageboardServerInterface::_PD_repoId);
  tcd->result = impl->getChildNames();


}

VS2::array_of_String* VS2::_objref_MessageboardServerInterface::getChildNames()
{
  _0RL_cd_446db2b6595c77cf_20000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_30000000, "getChildNames", 14);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for VS2::MessageboardServerInterface::getMessages

// Proxy call descriptor class. Mangled signature:
//  _cVS2_marray__of__MessageData
class _0RL_cd_446db2b6595c77cf_40000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_446db2b6595c77cf_40000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  VS2::array_of_MessageData_var result;
};

void _0RL_cd_446db2b6595c77cf_40000000::marshalReturnedValues(cdrStream& _n)
{
  (const VS2::array_of_MessageData&) result >>= _n;

}

void _0RL_cd_446db2b6595c77cf_40000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new VS2::array_of_MessageData;
  (VS2::array_of_MessageData&)result <<= _n;

}

const char* const _0RL_cd_446db2b6595c77cf_40000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_446db2b6595c77cf_50000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_446db2b6595c77cf_40000000* tcd = (_0RL_cd_446db2b6595c77cf_40000000*)cd;
  VS2::_impl_MessageboardServerInterface* impl = (VS2::_impl_MessageboardServerInterface*) svnt->_ptrToInterface(VS2::MessageboardServerInterface::_PD_repoId);
  tcd->result = impl->getMessages();


}

VS2::array_of_MessageData* VS2::_objref_MessageboardServerInterface::getMessages()
{
  _0RL_cd_446db2b6595c77cf_40000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_50000000, "getMessages", 12);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for VS2::MessageboardServerInterface::setHighlightedMessage

// Proxy call descriptor class. Mangled signature:
//  _cVS2_mMessageData_i_cstring
class _0RL_cd_446db2b6595c77cf_60000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_446db2b6595c77cf_60000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
  VS2::MessageData_var result;
};

void _0RL_cd_446db2b6595c77cf_60000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);

}

void _0RL_cd_446db2b6595c77cf_60000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();

}

void _0RL_cd_446db2b6595c77cf_60000000::marshalReturnedValues(cdrStream& _n)
{
  (const VS2::MessageData&) result >>= _n;

}

void _0RL_cd_446db2b6595c77cf_60000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new VS2::MessageData;
  (VS2::MessageData&)result <<= _n;

}

const char* const _0RL_cd_446db2b6595c77cf_60000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_446db2b6595c77cf_70000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_446db2b6595c77cf_60000000* tcd = (_0RL_cd_446db2b6595c77cf_60000000*)cd;
  VS2::_impl_MessageboardServerInterface* impl = (VS2::_impl_MessageboardServerInterface*) svnt->_ptrToInterface(VS2::MessageboardServerInterface::_PD_repoId);
  tcd->result = impl->setHighlightedMessage(tcd->arg_0);


}

VS2::MessageData* VS2::_objref_MessageboardServerInterface::setHighlightedMessage(const char* messageID)
{
  _0RL_cd_446db2b6595c77cf_60000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_70000000, "setHighlightedMessage", 22);
  _call_desc.arg_0 = messageID;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for VS2::MessageboardServerInterface::getHighlightedMessage

// Proxy call descriptor class. Mangled signature:
//  _cVS2_mMessageData
class _0RL_cd_446db2b6595c77cf_80000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_446db2b6595c77cf_80000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  VS2::MessageData_var result;
};

void _0RL_cd_446db2b6595c77cf_80000000::marshalReturnedValues(cdrStream& _n)
{
  (const VS2::MessageData&) result >>= _n;

}

void _0RL_cd_446db2b6595c77cf_80000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new VS2::MessageData;
  (VS2::MessageData&)result <<= _n;

}

const char* const _0RL_cd_446db2b6595c77cf_80000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_446db2b6595c77cf_90000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_446db2b6595c77cf_80000000* tcd = (_0RL_cd_446db2b6595c77cf_80000000*)cd;
  VS2::_impl_MessageboardServerInterface* impl = (VS2::_impl_MessageboardServerInterface*) svnt->_ptrToInterface(VS2::MessageboardServerInterface::_PD_repoId);
  tcd->result = impl->getHighlightedMessage();


}

VS2::MessageData* VS2::_objref_MessageboardServerInterface::getHighlightedMessage()
{
  _0RL_cd_446db2b6595c77cf_80000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_90000000, "getHighlightedMessage", 22);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for VS2::MessageboardServerInterface::getMessageWithId

// Local call call-back function.
static void
_0RL_lcfn_446db2b6595c77cf_a0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_446db2b6595c77cf_60000000* tcd = (_0RL_cd_446db2b6595c77cf_60000000*)cd;
  VS2::_impl_MessageboardServerInterface* impl = (VS2::_impl_MessageboardServerInterface*) svnt->_ptrToInterface(VS2::MessageboardServerInterface::_PD_repoId);
  tcd->result = impl->getMessageWithId(tcd->arg_0);


}

VS2::MessageData* VS2::_objref_MessageboardServerInterface::getMessageWithId(const char* messageID)
{
  _0RL_cd_446db2b6595c77cf_60000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_a0000000, "getMessageWithId", 17);
  _call_desc.arg_0 = messageID;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for VS2::MessageboardServerInterface::setMessage

// Proxy call descriptor class. Mangled signature:
//  _cboolean_i_cstring_i_cstring_i_cVS2_mUserData
class _0RL_cd_446db2b6595c77cf_b0000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_446db2b6595c77cf_b0000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
  ::CORBA::String_var arg_1_;
  const char* arg_1;
  VS2::UserData_var arg_2_;
  const VS2::UserData* arg_2;
  ::CORBA::Boolean result;
};

void _0RL_cd_446db2b6595c77cf_b0000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);
  _n.marshalString(arg_1,0);
  (const VS2::UserData&) *arg_2 >>= _n;

}

void _0RL_cd_446db2b6595c77cf_b0000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();
  arg_1_ = _n.unmarshalString(0);
  arg_1 = arg_1_.in();
  arg_2_ = new VS2::UserData;
  (VS2::UserData&)arg_2_ <<= _n;
  arg_2 = &arg_2_.in();

}

void _0RL_cd_446db2b6595c77cf_b0000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);

}

void _0RL_cd_446db2b6595c77cf_b0000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();

}

const char* const _0RL_cd_446db2b6595c77cf_b0000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_446db2b6595c77cf_c0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_446db2b6595c77cf_b0000000* tcd = (_0RL_cd_446db2b6595c77cf_b0000000*)cd;
  VS2::_impl_MessageboardServerInterface* impl = (VS2::_impl_MessageboardServerInterface*) svnt->_ptrToInterface(VS2::MessageboardServerInterface::_PD_repoId);
  tcd->result = impl->setMessage(tcd->arg_0, tcd->arg_1, *tcd->arg_2);


}

::CORBA::Boolean VS2::_objref_MessageboardServerInterface::setMessage(const char* message, const char* messageID, const ::VS2::UserData& uData)
{
  _0RL_cd_446db2b6595c77cf_b0000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_c0000000, "setMessage", 11);
  _call_desc.arg_0 = message;
  _call_desc.arg_1 = messageID;
  _call_desc.arg_2 = &(::VS2::UserData&) uData;

  _invoke(_call_desc);
  return _call_desc.result;


}


//
// Code for VS2::MessageboardServerInterface::deleteMessage

// Proxy call descriptor class. Mangled signature:
//  _cboolean_i_cstring_i_cVS2_mUserData
class _0RL_cd_446db2b6595c77cf_d0000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_446db2b6595c77cf_d0000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
  VS2::UserData_var arg_1_;
  const VS2::UserData* arg_1;
  ::CORBA::Boolean result;
};

void _0RL_cd_446db2b6595c77cf_d0000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);
  (const VS2::UserData&) *arg_1 >>= _n;

}

void _0RL_cd_446db2b6595c77cf_d0000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();
  arg_1_ = new VS2::UserData;
  (VS2::UserData&)arg_1_ <<= _n;
  arg_1 = &arg_1_.in();

}

void _0RL_cd_446db2b6595c77cf_d0000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);

}

void _0RL_cd_446db2b6595c77cf_d0000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();

}

const char* const _0RL_cd_446db2b6595c77cf_d0000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_446db2b6595c77cf_e0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_446db2b6595c77cf_d0000000* tcd = (_0RL_cd_446db2b6595c77cf_d0000000*)cd;
  VS2::_impl_MessageboardServerInterface* impl = (VS2::_impl_MessageboardServerInterface*) svnt->_ptrToInterface(VS2::MessageboardServerInterface::_PD_repoId);
  tcd->result = impl->deleteMessage(tcd->arg_0, *tcd->arg_1);


}

::CORBA::Boolean VS2::_objref_MessageboardServerInterface::deleteMessage(const char* messageID, const ::VS2::UserData& uData)
{
  _0RL_cd_446db2b6595c77cf_d0000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_e0000000, "deleteMessage", 14);
  _call_desc.arg_0 = messageID;
  _call_desc.arg_1 = &(::VS2::UserData&) uData;

  _invoke(_call_desc);
  return _call_desc.result;


}


//
// Code for VS2::MessageboardServerInterface::createNewMessage

// Local call call-back function.
static void
_0RL_lcfn_446db2b6595c77cf_f0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_446db2b6595c77cf_d0000000* tcd = (_0RL_cd_446db2b6595c77cf_d0000000*)cd;
  VS2::_impl_MessageboardServerInterface* impl = (VS2::_impl_MessageboardServerInterface*) svnt->_ptrToInterface(VS2::MessageboardServerInterface::_PD_repoId);
  tcd->result = impl->createNewMessage(tcd->arg_0, *tcd->arg_1);


}

::CORBA::Boolean VS2::_objref_MessageboardServerInterface::createNewMessage(const char* message, const ::VS2::UserData& uData)
{
  _0RL_cd_446db2b6595c77cf_d0000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_f0000000, "createNewMessage", 17);
  _call_desc.arg_0 = message;
  _call_desc.arg_1 = &(::VS2::UserData&) uData;

  _invoke(_call_desc);
  return _call_desc.result;


}


//
// Code for VS2::MessageboardServerInterface::getNextMessage

// Local call call-back function.
static void
_0RL_lcfn_446db2b6595c77cf_01000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_446db2b6595c77cf_80000000* tcd = (_0RL_cd_446db2b6595c77cf_80000000*)cd;
  VS2::_impl_MessageboardServerInterface* impl = (VS2::_impl_MessageboardServerInterface*) svnt->_ptrToInterface(VS2::MessageboardServerInterface::_PD_repoId);
  tcd->result = impl->getNextMessage();


}

VS2::MessageData* VS2::_objref_MessageboardServerInterface::getNextMessage()
{
  _0RL_cd_446db2b6595c77cf_80000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_01000000, "getNextMessage", 15);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for VS2::MessageboardServerInterface::getPreviousMessage

// Local call call-back function.
static void
_0RL_lcfn_446db2b6595c77cf_11000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_446db2b6595c77cf_80000000* tcd = (_0RL_cd_446db2b6595c77cf_80000000*)cd;
  VS2::_impl_MessageboardServerInterface* impl = (VS2::_impl_MessageboardServerInterface*) svnt->_ptrToInterface(VS2::MessageboardServerInterface::_PD_repoId);
  tcd->result = impl->getPreviousMessage();


}

VS2::MessageData* VS2::_objref_MessageboardServerInterface::getPreviousMessage()
{
  _0RL_cd_446db2b6595c77cf_80000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_11000000, "getPreviousMessage", 19);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for VS2::MessageboardServerInterface::connectToFather

// Proxy call descriptor class. Mangled signature:
//  _cVS2_mConnectInformationData_i_cVS2_mUserData
class _0RL_cd_446db2b6595c77cf_21000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_446db2b6595c77cf_21000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  VS2::UserData_var arg_0_;
  const VS2::UserData* arg_0;
  VS2::ConnectInformationData_var result;
};

void _0RL_cd_446db2b6595c77cf_21000000::marshalArguments(cdrStream& _n)
{
  (const VS2::UserData&) *arg_0 >>= _n;

}

void _0RL_cd_446db2b6595c77cf_21000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = new VS2::UserData;
  (VS2::UserData&)arg_0_ <<= _n;
  arg_0 = &arg_0_.in();

}

void _0RL_cd_446db2b6595c77cf_21000000::marshalReturnedValues(cdrStream& _n)
{
  (const VS2::ConnectInformationData&) result >>= _n;

}

void _0RL_cd_446db2b6595c77cf_21000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new VS2::ConnectInformationData;
  (VS2::ConnectInformationData&)result <<= _n;

}

const char* const _0RL_cd_446db2b6595c77cf_21000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_446db2b6595c77cf_31000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_446db2b6595c77cf_21000000* tcd = (_0RL_cd_446db2b6595c77cf_21000000*)cd;
  VS2::_impl_MessageboardServerInterface* impl = (VS2::_impl_MessageboardServerInterface*) svnt->_ptrToInterface(VS2::MessageboardServerInterface::_PD_repoId);
  tcd->result = impl->connectToFather(*tcd->arg_0);


}

VS2::ConnectInformationData* VS2::_objref_MessageboardServerInterface::connectToFather(const ::VS2::UserData& uData)
{
  _0RL_cd_446db2b6595c77cf_21000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_31000000, "connectToFather", 16);
  _call_desc.arg_0 = &(::VS2::UserData&) uData;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for VS2::MessageboardServerInterface::connectToChild

// Proxy call descriptor class. Mangled signature:
//  _cVS2_mConnectInformationData_i_cstring
class _0RL_cd_446db2b6595c77cf_41000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_446db2b6595c77cf_41000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
  VS2::ConnectInformationData_var result;
};

void _0RL_cd_446db2b6595c77cf_41000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);

}

void _0RL_cd_446db2b6595c77cf_41000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();

}

void _0RL_cd_446db2b6595c77cf_41000000::marshalReturnedValues(cdrStream& _n)
{
  (const VS2::ConnectInformationData&) result >>= _n;

}

void _0RL_cd_446db2b6595c77cf_41000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new VS2::ConnectInformationData;
  (VS2::ConnectInformationData&)result <<= _n;

}

const char* const _0RL_cd_446db2b6595c77cf_41000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_446db2b6595c77cf_51000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_446db2b6595c77cf_41000000* tcd = (_0RL_cd_446db2b6595c77cf_41000000*)cd;
  VS2::_impl_MessageboardServerInterface* impl = (VS2::_impl_MessageboardServerInterface*) svnt->_ptrToInterface(VS2::MessageboardServerInterface::_PD_repoId);
  tcd->result = impl->connectToChild(tcd->arg_0);


}

VS2::ConnectInformationData* VS2::_objref_MessageboardServerInterface::connectToChild(const char* childName)
{
  _0RL_cd_446db2b6595c77cf_41000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_51000000, "connectToChild", 15);
  _call_desc.arg_0 = childName;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for VS2::MessageboardServerInterface::publishOnChilds

// Proxy call descriptor class. Mangled signature:
//  _cboolean_i_cstring_i_cstring_i_cVS2_mUserData_i_cboolean
class _0RL_cd_446db2b6595c77cf_61000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_446db2b6595c77cf_61000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
  ::CORBA::String_var arg_1_;
  const char* arg_1;
  VS2::UserData_var arg_2_;
  const VS2::UserData* arg_2;
  ::CORBA::Boolean arg_3;
  ::CORBA::Boolean result;
};

void _0RL_cd_446db2b6595c77cf_61000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);
  _n.marshalString(arg_1,0);
  (const VS2::UserData&) *arg_2 >>= _n;
  _n.marshalBoolean(arg_3);

}

void _0RL_cd_446db2b6595c77cf_61000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();
  arg_1_ = _n.unmarshalString(0);
  arg_1 = arg_1_.in();
  arg_2_ = new VS2::UserData;
  (VS2::UserData&)arg_2_ <<= _n;
  arg_2 = &arg_2_.in();
  arg_3 = _n.unmarshalBoolean();

}

void _0RL_cd_446db2b6595c77cf_61000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);

}

void _0RL_cd_446db2b6595c77cf_61000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();

}

const char* const _0RL_cd_446db2b6595c77cf_61000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_446db2b6595c77cf_71000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_446db2b6595c77cf_61000000* tcd = (_0RL_cd_446db2b6595c77cf_61000000*)cd;
  VS2::_impl_MessageboardServerInterface* impl = (VS2::_impl_MessageboardServerInterface*) svnt->_ptrToInterface(VS2::MessageboardServerInterface::_PD_repoId);
  tcd->result = impl->publishOnChilds(tcd->arg_0, tcd->arg_1, *tcd->arg_2, tcd->arg_3);


}

::CORBA::Boolean VS2::_objref_MessageboardServerInterface::publishOnChilds(const char* message, const char* messageID, const ::VS2::UserData& uData, ::CORBA::Boolean schalter)
{
  _0RL_cd_446db2b6595c77cf_61000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_71000000, "publishOnChilds", 16);
  _call_desc.arg_0 = message;
  _call_desc.arg_1 = messageID;
  _call_desc.arg_2 = &(::VS2::UserData&) uData;
  _call_desc.arg_3 = schalter;

  _invoke(_call_desc);
  return _call_desc.result;


}


//
// Code for VS2::MessageboardServerInterface::publishOnFather

// Local call call-back function.
static void
_0RL_lcfn_446db2b6595c77cf_81000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_446db2b6595c77cf_b0000000* tcd = (_0RL_cd_446db2b6595c77cf_b0000000*)cd;
  VS2::_impl_MessageboardServerInterface* impl = (VS2::_impl_MessageboardServerInterface*) svnt->_ptrToInterface(VS2::MessageboardServerInterface::_PD_repoId);
  tcd->result = impl->publishOnFather(tcd->arg_0, tcd->arg_1, *tcd->arg_2);


}

::CORBA::Boolean VS2::_objref_MessageboardServerInterface::publishOnFather(const char* message, const char* messageID, const ::VS2::UserData& uData)
{
  _0RL_cd_446db2b6595c77cf_b0000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_81000000, "publishOnFather", 16);
  _call_desc.arg_0 = message;
  _call_desc.arg_1 = messageID;
  _call_desc.arg_2 = &(::VS2::UserData&) uData;

  _invoke(_call_desc);
  return _call_desc.result;


}


//
// Code for VS2::MessageboardServerInterface::saveMessage

// Local call call-back function.
static void
_0RL_lcfn_446db2b6595c77cf_91000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_446db2b6595c77cf_b0000000* tcd = (_0RL_cd_446db2b6595c77cf_b0000000*)cd;
  VS2::_impl_MessageboardServerInterface* impl = (VS2::_impl_MessageboardServerInterface*) svnt->_ptrToInterface(VS2::MessageboardServerInterface::_PD_repoId);
  tcd->result = impl->saveMessage(tcd->arg_0, tcd->arg_1, *tcd->arg_2);


}

::CORBA::Boolean VS2::_objref_MessageboardServerInterface::saveMessage(const char* message, const char* messageID, const ::VS2::UserData& uData)
{
  _0RL_cd_446db2b6595c77cf_b0000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_91000000, "saveMessage", 12);
  _call_desc.arg_0 = message;
  _call_desc.arg_1 = messageID;
  _call_desc.arg_2 = &(::VS2::UserData&) uData;

  _invoke(_call_desc);
  return _call_desc.result;


}


//
// Code for VS2::MessageboardServerInterface::notifyFather

// Proxy call descriptor class. Mangled signature:
//  void_i_cVS2_mUserData
class _0RL_cd_446db2b6595c77cf_a1000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_446db2b6595c77cf_a1000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

    
  
  static const char* const _user_exns[];

  VS2::UserData_var arg_0_;
  const VS2::UserData* arg_0;
};

void _0RL_cd_446db2b6595c77cf_a1000000::marshalArguments(cdrStream& _n)
{
  (const VS2::UserData&) *arg_0 >>= _n;

}

void _0RL_cd_446db2b6595c77cf_a1000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = new VS2::UserData;
  (VS2::UserData&)arg_0_ <<= _n;
  arg_0 = &arg_0_.in();

}

const char* const _0RL_cd_446db2b6595c77cf_a1000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_446db2b6595c77cf_b1000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_446db2b6595c77cf_a1000000* tcd = (_0RL_cd_446db2b6595c77cf_a1000000*)cd;
  VS2::_impl_MessageboardServerInterface* impl = (VS2::_impl_MessageboardServerInterface*) svnt->_ptrToInterface(VS2::MessageboardServerInterface::_PD_repoId);
  impl->notifyFather(*tcd->arg_0);


}

void VS2::_objref_MessageboardServerInterface::notifyFather(const ::VS2::UserData& uData)
{
  _0RL_cd_446db2b6595c77cf_a1000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_b1000000, "notifyFather", 13);
  _call_desc.arg_0 = &(::VS2::UserData&) uData;

  _invoke(_call_desc);



}


//
// Code for VS2::MessageboardServerInterface::saveFatherInformation

// Proxy call descriptor class. Mangled signature:
//  void_i_clong_i_cstring_i_cVS2_mConnectInformationData_i_cVS2_mUserData
class _0RL_cd_446db2b6595c77cf_c1000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_446db2b6595c77cf_c1000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

    
  
  static const char* const _user_exns[];

  ::CORBA::Long arg_0;
  ::CORBA::String_var arg_1_;
  const char* arg_1;
  VS2::ConnectInformationData_var arg_2_;
  const VS2::ConnectInformationData* arg_2;
  VS2::UserData_var arg_3_;
  const VS2::UserData* arg_3;
};

void _0RL_cd_446db2b6595c77cf_c1000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  _n.marshalString(arg_1,0);
  (const VS2::ConnectInformationData&) *arg_2 >>= _n;
  (const VS2::UserData&) *arg_3 >>= _n;

}

void _0RL_cd_446db2b6595c77cf_c1000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Long&)arg_0 <<= _n;
  arg_1_ = _n.unmarshalString(0);
  arg_1 = arg_1_.in();
  arg_2_ = new VS2::ConnectInformationData;
  (VS2::ConnectInformationData&)arg_2_ <<= _n;
  arg_2 = &arg_2_.in();
  arg_3_ = new VS2::UserData;
  (VS2::UserData&)arg_3_ <<= _n;
  arg_3 = &arg_3_.in();

}

const char* const _0RL_cd_446db2b6595c77cf_c1000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_446db2b6595c77cf_d1000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_446db2b6595c77cf_c1000000* tcd = (_0RL_cd_446db2b6595c77cf_c1000000*)cd;
  VS2::_impl_MessageboardServerInterface* impl = (VS2::_impl_MessageboardServerInterface*) svnt->_ptrToInterface(VS2::MessageboardServerInterface::_PD_repoId);
  impl->saveFatherInformation(tcd->arg_0, tcd->arg_1, *tcd->arg_2, *tcd->arg_3);


}

void VS2::_objref_MessageboardServerInterface::saveFatherInformation(::CORBA::Long id, const char* name, const ::VS2::ConnectInformationData& ciData, const ::VS2::UserData& uData)
{
  _0RL_cd_446db2b6595c77cf_c1000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_d1000000, "saveFatherInformation", 22);
  _call_desc.arg_0 = id;
  _call_desc.arg_1 = name;
  _call_desc.arg_2 = &(::VS2::ConnectInformationData&) ciData;
  _call_desc.arg_3 = &(::VS2::UserData&) uData;

  _invoke(_call_desc);



}


//
// Code for VS2::MessageboardServerInterface::notifyChildren

// Local call call-back function.
static void
_0RL_lcfn_446db2b6595c77cf_e1000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_446db2b6595c77cf_a1000000* tcd = (_0RL_cd_446db2b6595c77cf_a1000000*)cd;
  VS2::_impl_MessageboardServerInterface* impl = (VS2::_impl_MessageboardServerInterface*) svnt->_ptrToInterface(VS2::MessageboardServerInterface::_PD_repoId);
  impl->notifyChildren(*tcd->arg_0);


}

void VS2::_objref_MessageboardServerInterface::notifyChildren(const ::VS2::UserData& uData)
{
  _0RL_cd_446db2b6595c77cf_a1000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_e1000000, "notifyChildren", 15);
  _call_desc.arg_0 = &(::VS2::UserData&) uData;

  _invoke(_call_desc);



}


//
// Code for VS2::MessageboardServerInterface::saveChildInformation

// Local call call-back function.
static void
_0RL_lcfn_446db2b6595c77cf_f1000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_446db2b6595c77cf_c1000000* tcd = (_0RL_cd_446db2b6595c77cf_c1000000*)cd;
  VS2::_impl_MessageboardServerInterface* impl = (VS2::_impl_MessageboardServerInterface*) svnt->_ptrToInterface(VS2::MessageboardServerInterface::_PD_repoId);
  impl->saveChildInformation(tcd->arg_0, tcd->arg_1, *tcd->arg_2, *tcd->arg_3);


}

void VS2::_objref_MessageboardServerInterface::saveChildInformation(::CORBA::Long id, const char* name, const ::VS2::ConnectInformationData& ciData, const ::VS2::UserData& uData)
{
  _0RL_cd_446db2b6595c77cf_c1000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_f1000000, "saveChildInformation", 21);
  _call_desc.arg_0 = id;
  _call_desc.arg_1 = name;
  _call_desc.arg_2 = &(::VS2::ConnectInformationData&) ciData;
  _call_desc.arg_3 = &(::VS2::UserData&) uData;

  _invoke(_call_desc);



}


//
// Code for VS2::MessageboardServerInterface::createMessageSoap

// Proxy call descriptor class. Mangled signature:
//  _cboolean_i_cstring_i_cstring_i_clong_i_cVS2_mUserData
class _0RL_cd_446db2b6595c77cf_02000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_446db2b6595c77cf_02000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
  ::CORBA::String_var arg_1_;
  const char* arg_1;
  ::CORBA::Long arg_2;
  VS2::UserData_var arg_3_;
  const VS2::UserData* arg_3;
  ::CORBA::Boolean result;
};

void _0RL_cd_446db2b6595c77cf_02000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);
  _n.marshalString(arg_1,0);
  arg_2 >>= _n;
  (const VS2::UserData&) *arg_3 >>= _n;

}

void _0RL_cd_446db2b6595c77cf_02000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();
  arg_1_ = _n.unmarshalString(0);
  arg_1 = arg_1_.in();
  (::CORBA::Long&)arg_2 <<= _n;
  arg_3_ = new VS2::UserData;
  (VS2::UserData&)arg_3_ <<= _n;
  arg_3 = &arg_3_.in();

}

void _0RL_cd_446db2b6595c77cf_02000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);

}

void _0RL_cd_446db2b6595c77cf_02000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();

}

const char* const _0RL_cd_446db2b6595c77cf_02000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_446db2b6595c77cf_12000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_446db2b6595c77cf_02000000* tcd = (_0RL_cd_446db2b6595c77cf_02000000*)cd;
  VS2::_impl_MessageboardServerInterface* impl = (VS2::_impl_MessageboardServerInterface*) svnt->_ptrToInterface(VS2::MessageboardServerInterface::_PD_repoId);
  tcd->result = impl->createMessageSoap(tcd->arg_0, tcd->arg_1, tcd->arg_2, *tcd->arg_3);


}

::CORBA::Boolean VS2::_objref_MessageboardServerInterface::createMessageSoap(const char* message, const char* messageID, ::CORBA::Long serverNr, const ::VS2::UserData& uData)
{
  _0RL_cd_446db2b6595c77cf_02000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_12000000, "createMessageSoap", 18);
  _call_desc.arg_0 = message;
  _call_desc.arg_1 = messageID;
  _call_desc.arg_2 = serverNr;
  _call_desc.arg_3 = &(::VS2::UserData&) uData;

  _invoke(_call_desc);
  return _call_desc.result;


}


//
// Code for VS2::MessageboardServerInterface::modifyMessageSoap

// Local call call-back function.
static void
_0RL_lcfn_446db2b6595c77cf_22000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_446db2b6595c77cf_02000000* tcd = (_0RL_cd_446db2b6595c77cf_02000000*)cd;
  VS2::_impl_MessageboardServerInterface* impl = (VS2::_impl_MessageboardServerInterface*) svnt->_ptrToInterface(VS2::MessageboardServerInterface::_PD_repoId);
  tcd->result = impl->modifyMessageSoap(tcd->arg_0, tcd->arg_1, tcd->arg_2, *tcd->arg_3);


}

::CORBA::Boolean VS2::_objref_MessageboardServerInterface::modifyMessageSoap(const char* message, const char* messageID, ::CORBA::Long serverNr, const ::VS2::UserData& uData)
{
  _0RL_cd_446db2b6595c77cf_02000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_22000000, "modifyMessageSoap", 18);
  _call_desc.arg_0 = message;
  _call_desc.arg_1 = messageID;
  _call_desc.arg_2 = serverNr;
  _call_desc.arg_3 = &(::VS2::UserData&) uData;

  _invoke(_call_desc);
  return _call_desc.result;


}


//
// Code for VS2::MessageboardServerInterface::deleteMessageSoap

// Local call call-back function.
static void
_0RL_lcfn_446db2b6595c77cf_32000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_446db2b6595c77cf_d0000000* tcd = (_0RL_cd_446db2b6595c77cf_d0000000*)cd;
  VS2::_impl_MessageboardServerInterface* impl = (VS2::_impl_MessageboardServerInterface*) svnt->_ptrToInterface(VS2::MessageboardServerInterface::_PD_repoId);
  tcd->result = impl->deleteMessageSoap(tcd->arg_0, *tcd->arg_1);


}

::CORBA::Boolean VS2::_objref_MessageboardServerInterface::deleteMessageSoap(const char* messageID, const ::VS2::UserData& uData)
{
  _0RL_cd_446db2b6595c77cf_d0000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_32000000, "deleteMessageSoap", 18);
  _call_desc.arg_0 = messageID;
  _call_desc.arg_1 = &(::VS2::UserData&) uData;

  _invoke(_call_desc);
  return _call_desc.result;


}

VS2::_pof_MessageboardServerInterface::~_pof_MessageboardServerInterface() {}


omniObjRef*
VS2::_pof_MessageboardServerInterface::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::VS2::_objref_MessageboardServerInterface(ior, id);
}


::CORBA::Boolean
VS2::_pof_MessageboardServerInterface::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::VS2::MessageboardServerInterface::_PD_repoId))
    return 1;
  
  return 0;
}

const VS2::_pof_MessageboardServerInterface _the_pof_VS2_mMessageboardServerInterface;

VS2::_impl_MessageboardServerInterface::~_impl_MessageboardServerInterface() {}


::CORBA::Boolean
VS2::_impl_MessageboardServerInterface::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "getFatherName")) {

    _0RL_cd_446db2b6595c77cf_00000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_10000000, "getFatherName", 14, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "getChildNames")) {

    _0RL_cd_446db2b6595c77cf_20000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_30000000, "getChildNames", 14, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "getMessages")) {

    _0RL_cd_446db2b6595c77cf_40000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_50000000, "getMessages", 12, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "setHighlightedMessage")) {

    _0RL_cd_446db2b6595c77cf_60000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_70000000, "setHighlightedMessage", 22, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "getHighlightedMessage")) {

    _0RL_cd_446db2b6595c77cf_80000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_90000000, "getHighlightedMessage", 22, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "getMessageWithId")) {

    _0RL_cd_446db2b6595c77cf_60000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_a0000000, "getMessageWithId", 17, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "setMessage")) {

    _0RL_cd_446db2b6595c77cf_b0000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_c0000000, "setMessage", 11, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "deleteMessage")) {

    _0RL_cd_446db2b6595c77cf_d0000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_e0000000, "deleteMessage", 14, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "createNewMessage")) {

    _0RL_cd_446db2b6595c77cf_d0000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_f0000000, "createNewMessage", 17, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "getNextMessage")) {

    _0RL_cd_446db2b6595c77cf_80000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_01000000, "getNextMessage", 15, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "getPreviousMessage")) {

    _0RL_cd_446db2b6595c77cf_80000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_11000000, "getPreviousMessage", 19, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "connectToFather")) {

    _0RL_cd_446db2b6595c77cf_21000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_31000000, "connectToFather", 16, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "connectToChild")) {

    _0RL_cd_446db2b6595c77cf_41000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_51000000, "connectToChild", 15, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "publishOnChilds")) {

    _0RL_cd_446db2b6595c77cf_61000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_71000000, "publishOnChilds", 16, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "publishOnFather")) {

    _0RL_cd_446db2b6595c77cf_b0000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_81000000, "publishOnFather", 16, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "saveMessage")) {

    _0RL_cd_446db2b6595c77cf_b0000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_91000000, "saveMessage", 12, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "notifyFather")) {

    _0RL_cd_446db2b6595c77cf_a1000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_b1000000, "notifyFather", 13, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "saveFatherInformation")) {

    _0RL_cd_446db2b6595c77cf_c1000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_d1000000, "saveFatherInformation", 22, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "notifyChildren")) {

    _0RL_cd_446db2b6595c77cf_a1000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_e1000000, "notifyChildren", 15, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "saveChildInformation")) {

    _0RL_cd_446db2b6595c77cf_c1000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_f1000000, "saveChildInformation", 21, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "createMessageSoap")) {

    _0RL_cd_446db2b6595c77cf_02000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_12000000, "createMessageSoap", 18, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "modifyMessageSoap")) {

    _0RL_cd_446db2b6595c77cf_02000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_22000000, "modifyMessageSoap", 18, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "deleteMessageSoap")) {

    _0RL_cd_446db2b6595c77cf_d0000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_32000000, "deleteMessageSoap", 18, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
VS2::_impl_MessageboardServerInterface::_ptrToInterface(const char* id)
{
  if (id == ::VS2::MessageboardServerInterface::_PD_repoId)
    return (::VS2::_impl_MessageboardServerInterface*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::VS2::MessageboardServerInterface::_PD_repoId))
    return (::VS2::_impl_MessageboardServerInterface*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
VS2::_impl_MessageboardServerInterface::_mostDerivedRepoId()
{
  return ::VS2::MessageboardServerInterface::_PD_repoId;
}

VS2::LoginServerInterface_ptr VS2::LoginServerInterface_Helper::_nil() {
  return ::VS2::LoginServerInterface::_nil();
}

::CORBA::Boolean VS2::LoginServerInterface_Helper::is_nil(::VS2::LoginServerInterface_ptr p) {
  return ::CORBA::is_nil(p);

}

void VS2::LoginServerInterface_Helper::release(::VS2::LoginServerInterface_ptr p) {
  ::CORBA::release(p);
}

void VS2::LoginServerInterface_Helper::marshalObjRef(::VS2::LoginServerInterface_ptr obj, cdrStream& s) {
  ::VS2::LoginServerInterface::_marshalObjRef(obj, s);
}

VS2::LoginServerInterface_ptr VS2::LoginServerInterface_Helper::unmarshalObjRef(cdrStream& s) {
  return ::VS2::LoginServerInterface::_unmarshalObjRef(s);
}

void VS2::LoginServerInterface_Helper::duplicate(::VS2::LoginServerInterface_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

VS2::LoginServerInterface_ptr
VS2::LoginServerInterface::_duplicate(::VS2::LoginServerInterface_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

VS2::LoginServerInterface_ptr
VS2::LoginServerInterface::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


VS2::LoginServerInterface_ptr
VS2::LoginServerInterface::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

VS2::LoginServerInterface_ptr
VS2::LoginServerInterface::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_LoginServerInterface _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_LoginServerInterface* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_LoginServerInterface;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* VS2::LoginServerInterface::_PD_repoId = "IDL:VS2/LoginServerInterface:1.0";


VS2::_objref_LoginServerInterface::~_objref_LoginServerInterface() {
  
}


VS2::_objref_LoginServerInterface::_objref_LoginServerInterface(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::VS2::LoginServerInterface::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
VS2::_objref_LoginServerInterface::_ptrToObjRef(const char* id)
{
  if (id == ::VS2::LoginServerInterface::_PD_repoId)
    return (::VS2::LoginServerInterface_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::VS2::LoginServerInterface::_PD_repoId))
    return (::VS2::LoginServerInterface_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for VS2::LoginServerInterface::login

// Proxy call descriptor class. Mangled signature:
//  _cVS2_mLoginInformation_i_cVS2_mUserData
class _0RL_cd_446db2b6595c77cf_42000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_446db2b6595c77cf_42000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  VS2::UserData_var arg_0_;
  const VS2::UserData* arg_0;
  VS2::LoginInformation_var result;
};

void _0RL_cd_446db2b6595c77cf_42000000::marshalArguments(cdrStream& _n)
{
  (const VS2::UserData&) *arg_0 >>= _n;

}

void _0RL_cd_446db2b6595c77cf_42000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = new VS2::UserData;
  (VS2::UserData&)arg_0_ <<= _n;
  arg_0 = &arg_0_.in();

}

void _0RL_cd_446db2b6595c77cf_42000000::marshalReturnedValues(cdrStream& _n)
{
  (const VS2::LoginInformation&) result >>= _n;

}

void _0RL_cd_446db2b6595c77cf_42000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new VS2::LoginInformation;
  (VS2::LoginInformation&)result <<= _n;

}

const char* const _0RL_cd_446db2b6595c77cf_42000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_446db2b6595c77cf_52000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_446db2b6595c77cf_42000000* tcd = (_0RL_cd_446db2b6595c77cf_42000000*)cd;
  VS2::_impl_LoginServerInterface* impl = (VS2::_impl_LoginServerInterface*) svnt->_ptrToInterface(VS2::LoginServerInterface::_PD_repoId);
  tcd->result = impl->login(*tcd->arg_0);


}

VS2::LoginInformation* VS2::_objref_LoginServerInterface::login(const ::VS2::UserData& uData)
{
  _0RL_cd_446db2b6595c77cf_42000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_52000000, "login", 6);
  _call_desc.arg_0 = &(::VS2::UserData&) uData;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for VS2::LoginServerInterface::reg

// Proxy call descriptor class. Mangled signature:
//  _cboolean_i_cVS2_mUserData_i_cstring
class _0RL_cd_446db2b6595c77cf_62000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_446db2b6595c77cf_62000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  VS2::UserData_var arg_0_;
  const VS2::UserData* arg_0;
  ::CORBA::String_var arg_1_;
  const char* arg_1;
  ::CORBA::Boolean result;
};

void _0RL_cd_446db2b6595c77cf_62000000::marshalArguments(cdrStream& _n)
{
  (const VS2::UserData&) *arg_0 >>= _n;
  _n.marshalString(arg_1,0);

}

void _0RL_cd_446db2b6595c77cf_62000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = new VS2::UserData;
  (VS2::UserData&)arg_0_ <<= _n;
  arg_0 = &arg_0_.in();
  arg_1_ = _n.unmarshalString(0);
  arg_1 = arg_1_.in();

}

void _0RL_cd_446db2b6595c77cf_62000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);

}

void _0RL_cd_446db2b6595c77cf_62000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();

}

const char* const _0RL_cd_446db2b6595c77cf_62000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_446db2b6595c77cf_72000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_446db2b6595c77cf_62000000* tcd = (_0RL_cd_446db2b6595c77cf_62000000*)cd;
  VS2::_impl_LoginServerInterface* impl = (VS2::_impl_LoginServerInterface*) svnt->_ptrToInterface(VS2::LoginServerInterface::_PD_repoId);
  tcd->result = impl->reg(*tcd->arg_0, tcd->arg_1);


}

::CORBA::Boolean VS2::_objref_LoginServerInterface::reg(const ::VS2::UserData& uData, const char* regData)
{
  _0RL_cd_446db2b6595c77cf_62000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_72000000, "reg", 4);
  _call_desc.arg_0 = &(::VS2::UserData&) uData;
  _call_desc.arg_1 = regData;

  _invoke(_call_desc);
  return _call_desc.result;


}

VS2::_pof_LoginServerInterface::~_pof_LoginServerInterface() {}


omniObjRef*
VS2::_pof_LoginServerInterface::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::VS2::_objref_LoginServerInterface(ior, id);
}


::CORBA::Boolean
VS2::_pof_LoginServerInterface::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::VS2::LoginServerInterface::_PD_repoId))
    return 1;
  
  return 0;
}

const VS2::_pof_LoginServerInterface _the_pof_VS2_mLoginServerInterface;

VS2::_impl_LoginServerInterface::~_impl_LoginServerInterface() {}


::CORBA::Boolean
VS2::_impl_LoginServerInterface::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "login")) {

    _0RL_cd_446db2b6595c77cf_42000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_52000000, "login", 6, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "reg")) {

    _0RL_cd_446db2b6595c77cf_62000000 _call_desc(_0RL_lcfn_446db2b6595c77cf_72000000, "reg", 4, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
VS2::_impl_LoginServerInterface::_ptrToInterface(const char* id)
{
  if (id == ::VS2::LoginServerInterface::_PD_repoId)
    return (::VS2::_impl_LoginServerInterface*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::VS2::LoginServerInterface::_PD_repoId))
    return (::VS2::_impl_LoginServerInterface*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
VS2::_impl_LoginServerInterface::_mostDerivedRepoId()
{
  return ::VS2::LoginServerInterface::_PD_repoId;
}

POA_VS2::MessageboardServerInterface::~MessageboardServerInterface() {}

POA_VS2::LoginServerInterface::~LoginServerInterface() {}

